In [4]:
import re
import os
import math
import numpy as np

In [5]:
example = """0 3 6 9 12 15
1 3 6 10 15 21
10 13 16 21 30 45"""

In [8]:
def decompose(l):
    primeiroL = l.copy()

    diff = primeiroL.copy()
    i = 1
    while True:
        diff = np.diff(diff)
        print(diff)
        if all(np.equal(np.zeros(6 - i, dtype="int"), diff)):
            print("yes")
            break
        else:
            print("no")
        i += 1

In [9]:
l_of_lists = []
for l in example.split("\n"):
    l_int = [int(n) for n in l.split()]
    l_of_lists.append(l_int)

In [10]:
for l in l_of_lists:
    next_number = decompose(l)
    print(next_number)

[3 3 3 3 3]
<class 'numpy.ndarray'>
no
[0 0 0 0]
<class 'numpy.ndarray'>
yes
None
[2 3 4 5 6]
<class 'numpy.ndarray'>
no
[1 1 1 1]
<class 'numpy.ndarray'>
no
[0 0 0]
<class 'numpy.ndarray'>
yes
None
[ 3  3  5  9 15]
<class 'numpy.ndarray'>
no
[0 2 4 6]
<class 'numpy.ndarray'>
no
[2 2 2]
<class 'numpy.ndarray'>
no
[0 0]
<class 'numpy.ndarray'>
yes
None
